"""Add Meeting model

Revision ID: 187233ef820a
Revises: 5acb9ac39c15
Create Date: 2026-02-21 18:21:13.019322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187233ef820a'
down_revision: Union[str, Sequence[str], None] = '5acb9ac39c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUMMARIZED', 'FAILED', name='meetingstatus'), nullable=False),
    sa.Column('privacy_level', sa.Enum('PRIVATE', 'TEAM', 'PUBLIC', name='privacylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_sessions')
    # ### end Alembic commands ###
