"""Add PrivacyLevel enum constraint and columns

Revision ID: b063bf4c6ea6
Revises: c4cd99191bbd
Create Date: 2026-02-21 20:31:13.685593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b063bf4c6ea6'
down_revision: Union[str, Sequence[str], None] = 'c4cd99191bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_sessions', schema=None) as batch_op:
        batch_op.alter_column('privacy_level',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_level', sa.Enum('PRIVATE', 'TEAM', 'PUBLIC', name='privacylevel'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.drop_column('privacy_level')

    with op.batch_alter_table('meeting_sessions', schema=None) as batch_op:
        batch_op.alter_column('privacy_level',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)

    # ### end Alembic commands ###
