"""Add AutomationRule model

Revision ID: fcc97d4963fb
Revises: ac6e49ab502f
Create Date: 2026-02-21 18:53:21.328736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc97d4963fb'
down_revision: Union[str, Sequence[str], None] = 'ac6e49ab502f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.Enum('NEW_MEETING_SUMMARY', 'KEYWORD_IN_EVENT', 'DAILY_DIGEST', 'MANUAL', name='triggertype'), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('action_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_rules_user_id', 'automation_rules', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automation_rules_user_id', table_name='automation_rules')
    op.drop_table('automation_rules')
    op.execute("DROP TYPE IF EXISTS triggertype")
    # ### end Alembic commands ###
